### ISSUE TITLE
Unresolved issue marked as closed

### ISSUE THREAD

**Issue by glynkwei** [quabeeb/osu-tracker#5]
My previous issue (https://github.com/quabeeb/osu-tracker/issues/4) was marked as closed without any resolution or comments. In the future, please refrain from closing issues without a valid reason to do so.

`>.<`

**Comment by quabeeb** [comment]
There was no issue presented in #4 . If you have an actual issue, I'll be sure to look into it. 

This one will also be closed as a non-issue.
