### ISSUE TITLE
Osu tracker interface is lacking in emojis

### ISSUE THREAD

**Issue by glynkwei** [quabeeb/osu-tracker#6]
`._.`

**Comment by quabeeb** [comment]
This issue will be tracked through this branch:

https://github.com/quabeeb/osu-tracker/tree/feature/emoji

**Comment by quabeeb** [comment]
I'll merge #8 if you're satisfied @glynkwei

**Comment by quabeeb** [comment]
https://github.com/quabeeb/osu-tracker/pull/8
